# 参考文档：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#_standalone_mode
# 参考文档：http://my.oschina.net/buwei/blog/618756
---
spring:
  application: 
    name: himalaya-springcloud-eureka
  profiles:
    active: standalone

# Control log level TRACE < DEBUG < INFO < WARN < ERROR  
# 配置日志级别，让hibernate打印出执行的SQL  
logging:
  level:
    com:
      himalaya: info
  file: logs/${spring.application.name}.log
  
---
spring:
  profiles: standalone
server:
  port: 8090									# 指定该Eureka实例的端口
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/  

# 如果注释掉了security配置，则必须将security依赖从pom中移除        
#security:    #登陆验证
#  basic: 
#    enabled: false
#  user:
#    name: user
#    password: pwd123456
 
---
spring:
  profiles: peer1
server:
  port: 8090
eureka:
  instance:
    hostname: 192.168.179.128                              # 指定当profile=peer1时，主机名是peer1
  client:
    serviceUrl:
      defaultZone: http://192.168.179.129:8090/eureka/     # 将自己注册到peer2这个Eureka上面去

---
spring:
  profiles: peer2
server:
  port: 8090
eureka:
  instance:
    hostname: 192.168.179.129
  client:
    serviceUrl:
      defaultZone: http://192.168.179.128:8090/eureka/
      
      