spring: 
  application:  
    name: himalaya-springcloud-consumer

server: 
  port: 8070
  sessionTimeout: 30000
#  context-path: /consumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
      # defaultZone: http://user:pwd123456@localhost:8090/eureka/   # 注册到有安全验证的eureka server
  instance:
    prefer-ip-address: true
    
# 配置日志级别，让hibernate打印出执行的SQL
logging:                                
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

## INFO
info: 
  app: 
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@