server:
  port: 8080
  sessionTimeout: 30000
  context-path: /provider

spring:
  application:  
    name: himalaya-springcloud-provider
    
logging:
  level:
    root: INFO
    com.himalaya: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
  file: ./logs/app.log
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    metadata-map:
      my-metadata: custom configuration by provider    