# 参考文档：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#_standalone_mode
# 参考文档：http://my.oschina.net/buwei/blog/618756
---
spring:
  application: 
    name: himalaya-springcloud-eureka
  profiles:
    active: standalone

---
spring:
  profiles: standalone
server:
  port: 8090									# 指定该Eureka实例的端口
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/    
security:										#登陆验证
  basic:
    enabled: true
  user:
    name: user
    password: pwd123456
    
---
spring:
  profiles: peer1
server:
  port: 8091
eureka:
  instance:
    hostname: peer1                              # 指定当profile=peer1时，主机名是peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:8092/eureka/     # 将自己注册到peer2这个Eureka上面去

---
spring:
  profiles: peer2
server:
  port: 8092
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8091/eureka/
      
      