server:
  port: 8000
spring:
  application:
    name: himalaya-springcloud-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/
    
# 配置日志级别，让hibernate打印出执行的SQL
logging:                                
  level:
    root: INFO
    com.himalaya: DEBUG
  file: ./logs/app.log